version: '3'
services:
  sql:
    image: 'postgres:9.6'
    environment:
      POSTGRES_PASSWORD: ${BLOB_SQL_PASSWORD}
      POSTGRES_USER: ${BLOB_SQL_USER}
      POSTGRES_DB: ${BLOB_SQL_DB_NAME}
    ports:
      - "${BLOB_SQL_DB_PORT}:5432"
